Repository s4u/sign-maven-plugin, pull requests merged in 2020-12, with the labels that each got.

#2 allow skip execution
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner.java
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner36.java
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner40.java
  src/main/java/org/simplify4u/plugins/sign/ArtifactSignerFactory.java
  src/main/java/org/simplify4u/plugins/sign/SignMojo.java
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPKeyInfo.java
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPSigner.java
  src/test/java/org/simplify4u/plugins/sign/ArtifactSignerFactoryTest.java
  src/test/java/org/simplify4u/plugins/sign/SignMojoTest.java
Labels: enhancement

#6 support for sub keys
  pom.xml
  src/it/big-artifact/pom-test.xml
  src/it/pom-packaging/pom-test.xml
  src/it/standard-packaging/pom-test.xml
  src/it/verify-sign/keys-map.txt
  src/it/verify-sign/pom-test.xml
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPSecretKeyUtils.java
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPSigner.java
  src/test/java/org/simplify4u/plugins/sign/SignMojoTest.java
  src/test/java/org/simplify4u/plugins/sign/openpgp/PGPKeyInfoTest.java
  src/test/java/org/simplify4u/plugins/sign/openpgp/PGPSignerTest.java
  src/test/resources/priv-key-no-pass.asc
  src/test/resources/priv-key.asc
  src/test/resources/priv-sub-key-no-pass.asc
  src/test/resources/public-keys/BB/CE/BBCECF1D8377ED2E01001AE20EA8FD0653A5CC70.asc
  src/test/resources/public-keys/BC/06/BC065DCAA903A7785FF79E6EAC71B3E31C0C0D38.asc
Labels: enhancement

#9 junit-pioneer in test scope
  pom.xml
Labels: code quality

#10 cleanup GitHub Actions
  .github/workflows/gh-pages-deploy.yml
  .github/workflows/gh-pages-test.yml
Labels: code quality

#13 Using Java NIO API instead of Java IO API
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner36.java
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner40.java
  src/test/java/org/simplify4u/plugins/sign/openpgp/PGPKeyInfoTest.java
Labels: code quality

#14 Fixed typos and grammar
  src/site/markdown/key-prepare.md
Labels: code quality, documentation

#15 Remove HISTORY.md
  HISTORY.md
Labels: documentation

#16 Clear environment variable before tests.
  pom.xml
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPKeyInfo.java
  src/test/java/org/simplify4u/plugins/sign/openpgp/PGPKeyInfoTest.java
Labels: bug

#17 [8] Signature file name should contain version
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner.java
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner36.java
  src/main/java/org/simplify4u/plugins/sign/ArtifactSigner40.java
Labels: enhancement

#20 add expired key for testing #7
  src/test/resources/priv-expired-key-no-pass.asc
Labels: enhancement

#23 add LICENSE.txt
  LICENSE.txt
  pom.xml
Labels: documentation

#21 WIP: [19] Assert signature file name syntax
  src/it/big-artifact/postbuild.groovy
  src/it/pom-packaging/postbuild.groovy
  src/it/standard-packaging/postbuild.groovy
Labels: code quality

#24 Adding developer mkarg to POM
  pom.xml
Labels: documentation

#22 Validate key expiration time
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPSecretKeyUtils.java
  src/main/java/org/simplify4u/plugins/sign/openpgp/PGPSigner.java
  src/test/java/org/simplify4u/plugins/sign/openpgp/PGPSignerTest.java
Labels: enhancement
